version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: invoiceninja5-nginx
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html
      - ./dockerfiles/nginx:/etc/nginx/conf.d
      - ./dockerfiles/certs:/usr/share/certs
    depends_on:
      - php

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: invoiceninja5-php
    working_dir: /var/www/html
    tty: true
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    environment:
      SNAPPDF_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
      SNAPPDF_SKIP_DOWNLOAD: "true"

  mariadb:
    image: mariadb:latest
    container_name: invoiceninja5-mariadb
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE1}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD1}
      MYSQL_PASSWORD: ${DB_PASSWORD1}
      MYSQL_USER: ${DB_USERNAME1}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dockerfiles/mysql/my.cnf:/etc/my.cnf
    ports:
      - 3306:3306

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: invoiceninja5-composer
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: [ "composer", "--ignore-platform-reqs" ]
    environment:
      SNAPPDF_SKIP_DOWNLOAD: "true"

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: invoiceninja5-artisan
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: [ "php", "artisan" ]
    depends_on:
      - php
    environment:
      SNAPPDF_EXECUTABLE_PATH: "/usr/bin/chromium-browser"

  npm:
    image: node:14-alpine
    container_name: invoiceninja5-npm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: [ "npm" ]
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
    user: node

volumes:
  mysql-data:
